### ISSUE TITLE
Error rendering avro schema

### ISSUE THREAD

**Issue by niqdev** [cloudhut/kowl#147] opened 2020-11-23 13:08 UTC
Hi!
Thanks for the awesome project, the UI is really nice! I've got this error while trying to inspect a schema. I'm not sure tbh what's the actual cause.
Below the generated error, let me know if you need more details.
Thanks

```
Message:
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bfields%2C%20name%2C%20namespace%2C%20type%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack:
Ei@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1231151
p@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1232794
y@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1233907
ji/<@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1235995
Ta@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1245521
vc@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1286348
lu@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1276560
cu@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1276483
Zc@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1273492
$o/<@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1224877
t.unstable_runWithPriority@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1300458
Uo@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1224586
$o@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1224824
qo@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1224757
eu@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:1273783
Ge@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:24766
Xe@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:24348
We@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:20794
C</e.prototype.reportChanged@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:6541
Ce</t.prototype.setNewValue@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:14817
Sn</e.prototype.write@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:50773
Vt@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:32307
set@http://localhost:8000/static/js/2.aa56b853.chunk.js:2:35949
refreshSchemaDetails/<@http://localhost:8000/static/js/main.d8e01bed.chunk.js:1:74231

Components:
in td
in Cell
in tr
in BodyRow
in tbody
in Unknown
in table
in div
in div
in Unknown
in Unknown
in div
in Ne
in div
in div
in f
in div
in Er
in div
in x
in div
in w
in div
in a
in div
in ForwardRef
in a
in t
in t
in Pi
in ki
in Zi
in a
in main
in j
in Content
in section
in n
in Layout
in s
in section
in n
in Layout
in t
in t
in a
in a
in t
in t

Environment:
NODE_ENV : production
GIT_SHA  : a89848367df0c94cee64aa15345ed720fb17e83e
GIT_REF  : v1.2.1
TIMESTAMP: 1605538980
appName  : Kowl
```

**Comment by weeco** [comment] 2020-11-23 13:10
Hi @niqdev , this is most likely a duplicate of https://github.com/cloudhut/kowl/issues/143

Do you mind trying the latest docker build to see if this is fixed for you? See: https://quay.io/repository/cloudhut/kowl?tab=tags
If it is, I'm happy to create a new release tag for this.

**Comment by niqdev** [comment] 2020-11-23 13:17
Hi @weeco ! Sorry i was looking into other issues but i must have missed that 😓 
Yup, I've just pulled the latest images `master` and it works like a charm 😉 
Looking forward for a new release 🎉

**Closed** 2020-11-23 14:21 UTC

**Comment by weeco** [comment] 2020-11-23 16:08
Just created a new release for Kowl and Kowl Business :-)
