### ISSUE TITLE
NGINX support

### ISSUE THREAD

**Issue by sagitsofan** [cloudhut/kowl#117] opened 2020-08-17 08:04 UTC
Kowl does not support NGINX.

I added a NGINX in front of Kowl and the UI is broken, because that many static resources are absolute and not relative, according to the location configured inside the `nginx.conf`

I configured Kowl to be under `admin/kafka` path, but all the static resources are pointing to `/`
I saw in the Frontend a configuration with `%PUBLIC_URL%` but it needs to be exported as a environment variable from outside of the container ( like in docker compose yml example bellow )

Example for my nginx configuration:

 ```
       location /admin/kafka/ {
            proxy_pass             http://kowl:8077/;
            proxy_redirect  / /admin/kowl/;
            
            proxy_buffering                    off;
            proxy_set_header Host              $http_host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```

![image](https://user-images.githubusercontent.com/1827994/90372617-57631f80-e079-11ea-9318-24a2e3d54880.png)

![image](https://user-images.githubusercontent.com/1827994/90372142-9b095980-e078-11ea-8ad6-d2ff4f610e25.png)

**Comment by weeco** [comment] 2020-08-17 08:13
Hi,
I think this overlaps with #107 . We are already working on this, but I think you'd need to add a `X-Forwarded-For` header for the new solution to work.

**Comment by rikimaru0345** [comment] 2020-08-17 08:16
The header is named `X-Forwarded-Prefix`.
And there'll also be an option to set a static prefix, without having to use a proxy that sets (or strips) the header

**Comment by sagitsofan** [comment] 2020-08-17 08:25
The solution with the `X-Forwarded-Prefix` looks good! 
When will you release a version and a new docker image?

**Comment by rikimaru0345** [comment] 2020-08-17 08:26
When the feature is done, the github action should automatically create a new image.
I'll make sure to notify you here when its done though :D

**Comment by sagitsofan** [comment] 2020-08-17 08:29
Thank you! appreciates that

**Comment by rikimaru0345** [comment] 2020-08-17 11:35
@sagitsofan 

The feature is done 😄 
Please try it out and let me know if everything works.
See https://github.com/cloudhut/kowl/blob/master/docs/config/hosting.md#config-entries for documentation

**Comment by sagitsofan** [comment] 2020-08-18 08:55
@rikimaru0345 It works good now with the `X-Forwarded-Prefix` header.
I used the `master` tag for the docker image, will you create a new 1.1.1 version?

**Comment by weeco** [comment] 2020-08-18 09:08
This feature will be part of the 1.2 release. We don't have a due date for any of the upcoming releases but you can track the progress via the milestones here: https://github.com/cloudhut/kowl/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.2+release%22

**Comment by sagitsofan** [comment] 2020-08-18 09:11
So using in production the `master ` tag is safe ?

**Comment by weeco** [comment] 2020-08-18 09:29
No you should not use the `master` tag. Instead use one of the tags which refer to a specific commit. For example: `master-f0aa871d`: https://quay.io/repository/cloudhut/kowl?tab=tags. We always try to keep the master branch in a production ready state and we regularly use images from master as well. Obviously we can't provide extensive testing after each commit / merge to master.

We do test each version before we create a new release. The definition of "safe for production" varies a lot I guess.

**Comment by sagitsofan** [comment] 2020-08-18 09:36
Ok, I will do that.

Just found a critical bug, when i run the application with the
"X-Forwarded-Prefix" header, I cannot see the messages, and when i run it
without it, i can see the message.
After some small investigation, I found an error, seems like the web socket
is not working well with the new header?

[image: image.png]


Without proxy:
[image: image.png]

With proxy  ( no messages ):
[image: image.png]

**Comment by rikimaru0345** [comment] 2020-08-18 16:50
Which version (commit hash) were you testing?
Can you make sure it is f0aa871df38d1c6358440fb21f02168603bb6488 ?

I'll try to reproduce the error 👍 😄  Can you please post your NGINX config?

**Comment by sagitsofan** [comment] 2020-08-18 17:10
Using

**Comment by sagitsofan** [comment] 2020-08-18 17:13
Using the latest commit: f0aa871
My NGINX configuration:
  ```
  location /admin {
        resolver 127.0.0.11;

        location /admin/kafka/ {
            proxy_pass                              http://kowl:8077/;
            proxy_set_header X-Forwarded-Prefix     /admin/kafka/;
        }
    }
```

yml config:
```
kafka:
  brokers:
    - kafka1:19092

server:
  listenPort: 8077
  setBasePathFromXForwardedPrefix: true

```
![image](https://user-images.githubusercontent.com/1827994/90543866-eb72db00-e18e-11ea-8916-1f8e839e24f4.png)

**Comment by rikimaru0345** [comment] 2020-08-18 17:48
Ah, do you happen to have a docker-compose file that I can use to reproduce the error? 😄

**Comment by sagitsofan** [comment] 2020-08-18 18:03
Ah, not something completed that i can send, because its used in docker swarm with multiple compose overrides.
I can create something, but it will take me some time

**Comment by sagitsofan** [comment] 2020-08-30 06:17
@rikimaru0345 I created a small project that you can download and reproduce the error:
https://github.com/sagitsofan/KowlConfiguration

**Comment by rikimaru0345** [comment] 2020-08-31 08:41
Thanks, I will take a look this evening!

**Comment by rikimaru0345** [comment] 2020-08-31 17:46
@sagitsofan 
Just tried it, seems like the nginx dockerfile is missing?

```
$ docker-compose -f docker-compose.yml up
WARNING: Some services (zoo1) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Building nginx
ERROR: Cannot locate specified Dockerfile: Dockerfile 
```

**Comment by sagitsofan** [comment] 2020-08-31 17:55
Just pull the images manually and then run it again:

docker pull nginx:1.19-alpine
docker pull zookeeper:3.4.9
docker pull confluentinc/cp-kafka:5.5.0
docker pull quay.io/cloudhut/kowl:master

**Comment by rikimaru0345** [comment] 2020-08-31 18:22
Seems like the issue is really simple. nginx must be configured to keep passing the upgrade header.
Just adding this to the nginx config did the trick.

```
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```

**Comment by sagitsofan** [comment] 2020-09-01 07:44
Works great, Thank you @rikimaru0345

**Closed** 2020-09-01 08:20 UTC
